/**
 * This class is generated by jOOQ
 */
package eu.creatingfuture.propeller.blocklyprop.db;


import eu.creatingfuture.propeller.blocklyprop.db.tables.Project;
import eu.creatingfuture.propeller.blocklyprop.db.tables.ProjectTag;
import eu.creatingfuture.propeller.blocklyprop.db.tables.Tag;
import eu.creatingfuture.propeller.blocklyprop.db.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Blocklyprop extends SchemaImpl {

	private static final long serialVersionUID = -1055471880;

	/**
	 * The reference instance of <code>blocklyprop</code>
	 */
	public static final Blocklyprop BLOCKLYPROP = new Blocklyprop();

	/**
	 * No further instances allowed
	 */
	private Blocklyprop() {
		super("blocklyprop");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Project.PROJECT,
			ProjectTag.PROJECT_TAG,
			Tag.TAG,
			User.USER);
	}
}
