/**
 * This class is generated by jOOQ
 */
package eu.creatingfuture.propeller.blocklyprop.db;


import eu.creatingfuture.propeller.blocklyprop.db.tables.Project;
import eu.creatingfuture.propeller.blocklyprop.db.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in blocklyprop
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table blocklyprop.project
	 */
	public static final Project PROJECT = eu.creatingfuture.propeller.blocklyprop.db.tables.Project.PROJECT;

	/**
	 * The table blocklyprop.user
	 */
	public static final User USER = eu.creatingfuture.propeller.blocklyprop.db.tables.User.USER;
}
