<%--
    Document   : COPPA policy page
    Created on : 08-MAY-2017
    Author     : J. Ewald
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ include file="/WEB-INF/includes/include.jsp"%>

<html>
    <head>
        <%@ include file="/WEB-INF/includes/pageparts/head/basic.jsp"%>
    </head>
    <body>

        <%@ include file="/WEB-INF/includes/pageparts/menu.jsp"%>

        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12">
                    <h3><fmt:message key="coppa.policy.title" /></h3>
                    <div>
                        <h2>Parallax BlocklyProp Privacy Policies</h2>
                        <p>Parallax Inc., including the BlocklyProp system, is committed to protecting the privacy of children who use our sites and applications. This online privacy policy explains our information collection, disclosure, and parental notification and consent practices with respect to information provided by children under the age of 13 (“child” or “children”). This policy is in accordance with the U.S. Children’s Online Privacy Protection Act ("COPPA") and the Family Education Records Privacy Act ("FERPA"), and outlines our practices in the United States and Latin America regarding children’s personal information.</p>
                        <h3>The Information We Collect From Children, How We Use It, and How and When We Communicate With Parents</h3>
                        <p>In any instance that we collect personal information from a child, we will retain that information only so long as reasonably necessary to fulfill the activity request or allow the child to continue to participate in the activity, and ensure the security of our users and our services, or as required by law. In the event we discover we have collected information from a child in a manner inconsistent with COPPA’s requirements, we will either delete the information or immediately seek the parent’s consent for that collection.</p>
                        <h4>Registration</h4>
                        <p>Children can register with our site to learn and create with the BlocklyProp system. During the registration process, we may ask the child to provide certain information for notification and security purposes, including a parent or guardian’s email address, the child’s member or account username, and password. We also may ask for birth dates from children to validate their ages. We strongly advise children never to provide any personal information in their usernames. We will not require a child to provide more information than is reasonably necessary in order to use the BlocklyProp system.</p>
                        <p>About the collection of parent email address: Consistent with the requirements of COPPA, on any child-targeted site or application, or in any instance where we ask for age and determine the user is age 12 or under, we will ask for a parent or guardian email address before we collect any personal information from the child. If you believe your child is participating in an activity that collects personal information and you or another parent/guardian have NOT received an email providing notice or seeking your consent, please feel free to contact us at education@parallax.com. We will not use parent e-mails provided for parental consent purposes to market to the parent unless the parent has expressly opted in to email marketing or has separately participated in an activity that allows for such email contact.</p>
                        <h4>Content Generated by a Child</h4>
                        <p>The BlocklyProp system allows children to create or manipulate content and save it online. Although the BlocklyProp system does not collect or share personal information, it is possible for a child to enter information into open text boxes and fields.  Therefore, we encourage you to actively participate in your child’s learning and activity on the BlocklyProp system.  If we become aware of anything shared publicly that appears to be personal in nature from any of our users under 13 years of age, we will remove and delete it immediately.</p>
                        <h4>About Parental Notification and Consent:</h4>
                        <p>Email Notification: When a child registers an account on the BlocklyProp system, COPPA requires that we notify a parent or guardian’s by email. In the email we will explain what information we are collecting, and how we plan to use it.</p>
                        <p>Email Consent: The email sent to a parent or guardian as a notification will contain a link that, when clicked, will allow the parent to provide consent to allow their child to share their creations publicly with the BlocklyProp community of users.</p>
                        <p>Teacher consent in lieu of a parent. With regard to school-based activities, COPPA allows teachers and school administrators to act in the stead of parents to provide consent for the collection of personal information from children. Schools should always notify parents about these activities. For more information on parental rights with respect to a child’s educational record under the Family Educational Rights and Privacy Act (FERPA), please visit the FERPA site.</p>
                        <h4>Email Contact with a Child</h4>
                        <p>On occasion, in order to respond to a question or request from a child, Parallax may need to ask for the child’s online contact information, such as an email address. Parallax will delete this information immediately after responding to the question or request.</p>
                        <h4>Third-parties and outside entities</h4>
                        <p>Parallax Inc. does not share, sell, or disclose any user or customer information with third-parties or outside entities, unless that entity is a law-enforcement agency that has obtained the legal authority to collect it.</p>
                        <h4>Persistent Identifiers</h4>
                        <p>When children interact with us, certain information may automatically be collected to make more useful and secure. Examples include the type of computer operating system, the child’s IP address or mobile device identifier, the web browser, and information regarding the online or mobile service provider. This information is collected using technologies such as cookies, flash cookies, web beacons, and other unique identifiers. This data is principally used for internal purposes only, in order to:</p>                        
                        <ul>
                            <li>provide children with access to features and activities on our site and application</li>
                            <li>customize content and improve our site and application</li>
                            <li>conduct research and analysis to address the performance of our site and application</li>
                            <li>generate anonymous reporting</li>
                        </ul>
                        <p>Please contact us at the mailing address, email, or phone number below with questions about the operators’ privacy policies and collection and use practices:</p>
                        <p>Parallax Inc.<br/>
                            599 Menlo Drive<br/>
                            Rocklin, CA 95765<br/>
                            United States of America<br/>
                            <br/>
                            Phone: (888) 512-1024<br/>
                            Email: education@parallax.com<br/>
                        </p>
                        <p>At any time, parents can refuse to permit us to collect further personal information from their children in association with a particular account, and can request that we delete from our records the personal information we have collected in connection with that account. Please keep in mind that a request to delete records may lead to a termination of an account, membership, or other service.</p>
                        <p>In any correspondence such as e-mail or mail, please include the child’s username and the parent’s email address and telephone number. To protect children’s privacy and security, we will take reasonable steps to help verify a parent’s identity before granting access to any personal information.</p>
                    </div>
                    <p><a href="<url:getUrl url="/index"/>">Go to home</a></p>
                </div>
            </div>
        </div>

        <%@ include file="/WEB-INF/includes/pageparts/footer.jsp"%>

    </body>
</html>