// Do not edit this file; automatically generated by build.py.
"use strict";
document.write('<script type="text/javascript" src="../../../closure-library-read-only/closure/goog/base.js"></script>');
(function() {
  var filenames = ['blockly.js', 'block.js', 'block_svg.js', 'blocks.js', 'bubble.js', 'comment.js', 'connection.js', 'contextmenu.js', 'css.js', 'field.js', 'field_angle.js', 'field_dropdown.js', 'field_checkbox.js', 'field_colour.js', 'field_date.js', 'field_image.js', 'field_label.js', 'field_textinput.js', 'field_variable.js', 'field_pointer.js', 'flyout.js', 'generator.js', 'icon.js', 'inject.js', 'input.js', 'msg.js', 'mutator.js', 'names.js', 'procedures.js', 'realtime-client-utils.js', 'realtime.js', 'scrollbar.js', 'toolbox.js', 'tooltip.js', 'trashcan.js', 'utils.js', 'variables.js', 'pointers.js', 'warning.js', 'widgetdiv.js', 'workspace.js', 'workspace_svg.js', 'xml.js'];
  for (var x = 0; x < filenames.length; x++) {
    document.write('<script type="text/javascript" src="../../core/' + filenames[x] + '"></script>');
  }
})();
