/**
 * This class is generated by jOOQ
 */
package eu.creatingfuture.propeller.blocklyprop;


import javax.annotation.Generated;

import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Blocklyprop extends SchemaImpl {

	private static final long serialVersionUID = -263281258;

	/**
	 * The reference instance of <code>blocklyprop</code>
	 */
	public static final Blocklyprop BLOCKLYPROP = new Blocklyprop();

	/**
	 * No further instances allowed
	 */
	private Blocklyprop() {
		super("blocklyprop");
	}
}
